source :rubygems

gem 'rake'
gem 'patron'
gem 'multi_json'
gem 'oj'
gem 'yajl-ruby', :require => 'yajl'
gem 'righttp'
gem 'rest-client', :require => 'restclient'
gem 'httprb'
gem 'httpclient'
gem 'httparty'
gem 'curb'
gem 'rufus-jig', :require => 'rufus/jig'
gem 'eventmachine'
gem 'em-http-request', '~>1.0.2'
gem 'net-http-persistent', :require => 'net/http/persistent'
gem 'typhoeus'
gem 'excon'
