source :rubygems

gem 'rake'
gem 'patron'
gem 'yajl-ruby', :require => 'yajl'
gem 'righttp'
gem 'rest-client', :require => 'restclient'
gem 'httprb'
gem 'httpclient'
gem 'httparty'
gem 'curb'
gem 'rufus-jig', :require => 'rufus/jig'
gem 'typhoeus'
gem 'eventmachine'
gem 'em-http-request'